### ISSUE TITLE
misc docu 

### ISSUE THREAD

**Issue by sbrockhaus** [maierhofert/classiFunc#3]
- [x] document and export `classiFunc:::predict.classiKnn`
- [x] use kamel case for all functions (and data sets?)
- [x] for `classiKernel`, add a code example in the help with an existing kernel function

- [x] in package description, Fuchs et al., (2015); use @references, @author 
- [x] ... derivative or arbitrary order

**Comment by maierhofert** [comment]
predict.classiKernel was documented as well.
